# Name of the experiment (used for log filename and output directory)
experiment_name: comstock_15min_1week

# Path to the CSV file containing the time-series data (one row per timestamp, one column per variable)
data_file: dataset/comstock/comstock_15min_small.csv         

# Path to the CSV file with labels for each appliance (each appliance is a separate column)
label_file: dataset/comstock/comstock_15min_labels.csv

# Number of data poionts (e.g., 4*24*7 for one week of 15-minutely data)
data_limit: 672

# Proportion of the dataset to be used as the test set
test_size: 0.3

# Directory where the experiment outputs (results and logs) will be stored
results_dir: results/

# List of appliances to evaluate; these names should match columns in the label file
appliance_list:
  - cooling_ON
  - fans_ON
  # - heat_rejection_ON
  # - heating_ON
  # - refrigeration_ON
  # - water_systems_ON

# List of models to train and evaluate (all supported models from sktime)
models:
  - Dummy
  - Rocket
  - Arsenal
  # - Minirocket
  # - TimeSeriesForest
  # - Rise
  # - DrCIF
  # - BOSS
  # - eBOSS
  # - cBOSS
  # - KNNeucli
